[MANIFEST]
	version = "1.0"

[PLUGIN]
	name = "plgLavaboomSample"
	type = "angular"
	version = "1.0"
	belongsTo = "LavaUtils"
	description = "Sample plugin"

	moduleName = "LavaUtils"

	dependencies = [
	]

	productionOnlyDependencies = [
		"plugin-templates"
	]